//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string userID { get; set; }
        public string userName { get; set; }
        public string fatherName { get; set; }
        public string userAdress { get; set; }
        public string phoneNo { get; set; }
        public string CNIC { get; set; }
        public Nullable<System.DateTime> dateOFBirth { get; set; }
        public Nullable<System.DateTime> admissionDate { get; set; }
        public Nullable<bool> status { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    }
}
